/*
 * This source file was generated by the Gradle 'init' task
 */
package com.orel6505.pgames;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import static org.junit.jupiter.api.Assertions.*;

import com.orel6505.pgames.player.*;
import com.orel6505.pgames.game.*;

class AppTest {
    @Test
    void randomPlayerTest() {
        Assertions.assertDoesNotThrow(() -> {
            //execute code that you expect not to throw Exceptions.
            Player p1 = new RandomPlayer("User A");
            Player p2 = new RandomPlayer("User B");
            Game game = new RockPaperScissors(p1, p2);
            game.play(10);
            System.out.println(p1.getName()+" got "+p1.getScore()+ " and "
                +p2.getName()+" got "+p2.getScore());
        });
    }
}
